sensio_framework_extra:
    router:
        annotations: false
    view:
        annotations: false
    request:
        converters: true
        # maybe disable this one day ane explicitly state ParamConverter annotations
        auto_convert: true