version: '3.7'
services:
    database:
        image: 'postgres:12-alpine'
        environment:
            POSTGRES_PASSWORD: idm
            POSTGRES_USER: idm
            POSTGRES_DB: idm
        ports:
            # uses a different port to avoid clash with a running KLMS instance
          - '5433:5432'
