restcontrollers:
    resource: ../../src/Controller/Rest/
    type: annotation
    prefix: /api

controllers:
    resource: ../../src/Controller/Admin/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
